name: Python CI

on:
  push:
    branches:
      - main  # Trigger workflow only on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow when a PR is opened against the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu to run the workflow

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checks out your code in the workflow

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the Python version you want to use (e.g., 3.8 or 3.x)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installs the dependencies from requirements.txt
    
    - name: Check if database exists
      run: |
        ls -l student.db  # Check if the database file exists
    
    - name: Run tests
      run: |
        python -m unittest discover  # Adjust this command if you're using other testing frameworks
        # or run specific test files here

    - name: Run the main script (Optional)
      run: |
        python main.py  # If you want to run the main script as part of the workflow

    - name: Upload Test Results (Optional)
      if: always()
      run: |
        # If you are using test frameworks like pytest, you can upload results here
        # e.g. using the `actions/upload-artifact@v2` action to upload test results
